version: '3'

tasks:
  default:
    cmds:
      - task: test
      - task: build

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

  build:
    desc: Build ps9s binary
    cmds:
      - go build -o ps9s ./cmd/ps9s
