# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ps9s < Formula
  desc "AWS Parameter Store TUI"
  homepage "https://github.com/caseycs/ps9s"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.1/ps9s_0.1.1_darwin_amd64.tar.gz"
      sha256 "e457ac57cb099d4fd31111cb6ef968c615f69a39af93764dff7b4c180c898ef3"

      def install
        bin.install "ps9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.1/ps9s_0.1.1_darwin_arm64.tar.gz"
      sha256 "03675b2e226b006a192ef4f2db1b903a0644ffc42acdcccf237581c5cca20fdc"

      def install
        bin.install "ps9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.1/ps9s_0.1.1_linux_amd64.tar.gz"
      sha256 "0480b32bb97de53771134bb8f5d32195861ae97a0edbb592d496b7d3413562a3"
      def install
        bin.install "ps9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.1/ps9s_0.1.1_linux_arm64.tar.gz"
      sha256 "2f78c288146536d36aea6d27f2c7cc5c08f683fc7ed27c9ad7191beecacd3bc2"
      def install
        bin.install "ps9s"
      end
    end
  end

  test do
    system "#{bin}/ps9s", "--help"
  end
end
